export const mockUserProfile = {
  name: "Hitendra Kotamraju",
  role: "Senior Cloud & DevOps Engineer",
  location: "United Kingdom",
  email: "hitesh.iat1@gmail.com",
  experience: 10,
  profileStrength: 82,
  cvReadiness: 91,
  jobMatchAverage: 76,
  applicationsThisWeek: 8,
  interviewsScheduled: 2,
  followUpsDue: 3,
  targetRoles: ["DevOps Engineer", "Cloud Architect", "SRE", "Platform Engineer"],
  skills: ["AWS", "Azure", "GCP", "Kubernetes", "Terraform", "Python", "Docker", "CI/CD", "Prometheus", "Grafana"],
  visaRequired: false,
}

export const mockJobs = [
  {
    id: "j1",
    title: "Senior DevOps Engineer",
    company: "Barclays Technology",
    location: "London, UK",
    type: "Permanent",
    salaryMin: 85000,
    salaryMax: 110000,
    currency: "GBP",
    matchScore: 92,
    description: "Lead the design and implementation of cloud-native infrastructure on AWS and Azure. Drive platform engineering initiatives and mentor junior engineers.",
    requirements: ["5+ years DevOps experience", "AWS/Azure certification", "Kubernetes", "Terraform", "CI/CD pipelines"],
    url: "https://www.linkedin.com/jobs",
    postedDate: "2026-05-24",
    sourceSite: "linkedin",
    category: "DevOps",
    visaSponsorship: false,
  },
  {
    id: "j2",
    title: "Azure Cloud Architect",
    company: "KPMG Digital",
    location: "London, UK (Hybrid)",
    type: "Permanent",
    salaryMin: 95000,
    salaryMax: 130000,
    currency: "GBP",
    matchScore: 87,
    description: "Design enterprise-grade Azure architectures for FTSE 100 clients. Lead cloud migration programmes and governance frameworks.",
    requirements: ["Azure Expert certification", "Enterprise architecture experience", "Azure Landing Zones", "Cost optimisation", "Team leadership"],
    url: "https://www.linkedin.com/jobs",
    postedDate: "2026-05-23",
    sourceSite: "cwjobs",
    category: "Cloud",
    visaSponsorship: false,
  },
  {
    id: "j3",
    title: "Site Reliability Engineer",
    company: "Monzo Bank",
    location: "London, UK (Remote-friendly)",
    type: "Permanent",
    salaryMin: 90000,
    salaryMax: 115000,
    currency: "GBP",
    matchScore: 84,
    description: "Join Monzo's SRE team to improve system reliability, implement SLOs, and drive incident response improvements across the platform.",
    requirements: ["SRE experience", "Go or Python", "Prometheus/Grafana", "Kubernetes", "Incident management"],
    url: "https://www.linkedin.com/jobs",
    postedDate: "2026-05-22",
    sourceSite: "linkedin",
    category: "SRE",
    visaSponsorship: false,
  },
  {
    id: "j4",
    title: "Platform Engineer — GCP",
    company: "Sky Technology",
    location: "Osterley, UK (Hybrid)",
    type: "Permanent",
    salaryMin: 80000,
    salaryMax: 105000,
    currency: "GBP",
    matchScore: 79,
    description: "Build and maintain Sky's internal developer platform on GCP. Work with Backstage, ArgoCD, and Helm to streamline developer workflows.",
    requirements: ["GCP experience", "Platform engineering", "Backstage/Internal developer portals", "ArgoCD", "Helm"],
    url: "https://www.cwjobs.co.uk",
    postedDate: "2026-05-21",
    sourceSite: "cwjobs",
    category: "Platform",
    visaSponsorship: false,
  },
  {
    id: "j5",
    title: "Lead DevOps Engineer (Contract)",
    company: "Lloyds Banking Group",
    location: "Remote, UK",
    type: "Contract",
    salaryMin: 600,
    salaryMax: 750,
    currency: "GBP/day",
    matchScore: 88,
    description: "6-month contract to lead DevOps transformation for Lloyds' retail banking division. Azure DevOps, Kubernetes, and Terraform focus.",
    requirements: ["Azure DevOps", "Kubernetes", "Terraform", "Banking sector experience preferred", "SC clearance eligible"],
    url: "https://www.cv-library.co.uk",
    postedDate: "2026-05-25",
    sourceSite: "cv-library",
    category: "DevOps",
    visaSponsorship: false,
  },
  {
    id: "j6",
    title: "Cloud Infrastructure Engineer",
    company: "Ocado Technology",
    location: "Hatfield, UK (Hybrid)",
    type: "Permanent",
    salaryMin: 75000,
    salaryMax: 95000,
    currency: "GBP",
    matchScore: 73,
    description: "Work on Ocado's proprietary cloud platform powering grocery fulfilment worldwide. Heavy AWS focus with custom tooling.",
    requirements: ["AWS advanced", "Python", "Terraform", "Kafka", "Microservices architecture"],
    url: "https://www.totaljobs.com",
    postedDate: "2026-05-20",
    sourceSite: "totaljobs",
    category: "Cloud",
    visaSponsorship: true,
  },
  {
    id: "j7",
    title: "DevSecOps Engineer",
    company: "BAE Systems Digital Intelligence",
    location: "London / Guildford (Hybrid)",
    type: "Permanent",
    salaryMin: 82000,
    salaryMax: 108000,
    currency: "GBP",
    matchScore: 68,
    description: "Embed security into CI/CD pipelines for defence and government programmes. SAST, DAST, container scanning, and secrets management.",
    requirements: ["DevSecOps experience", "Snyk/Aqua/Trivy", "SonarQube", "Vault", "SC/DV clearance or eligible"],
    url: "https://www.linkedin.com/jobs",
    postedDate: "2026-05-19",
    sourceSite: "linkedin",
    category: "DevSecOps",
    visaSponsorship: false,
  },
  {
    id: "j8",
    title: "Kubernetes Platform Architect",
    company: "Nationwide Building Society",
    location: "Swindon, UK (Hybrid)",
    type: "Permanent",
    salaryMin: 100000,
    salaryMax: 135000,
    currency: "GBP",
    matchScore: 81,
    description: "Define Nationwide's Kubernetes platform strategy. Lead the adoption of service mesh, multi-cluster federation, and developer experience improvements.",
    requirements: ["Kubernetes expert", "Istio/Linkerd", "Multi-cloud", "Architecture experience", "Financial services preferred"],
    url: "https://www.reed.co.uk",
    postedDate: "2026-05-22",
    sourceSite: "reed",
    category: "Platform",
    visaSponsorship: false,
  },
]

export const mockApplications = [
  {
    id: "a1",
    jobTitle: "Senior DevOps Engineer",
    company: "Barclays Technology",
    location: "London, UK",
    status: "interviewing" as const,
    appliedDate: "2026-05-15",
    followUpDate: "2026-05-28",
    notes: "Technical interview scheduled for 28th May. Prepare Kubernetes and AWS scenarios.",
    matchScore: 92,
  },
  {
    id: "a2",
    jobTitle: "Lead DevOps Engineer (Contract)",
    company: "Lloyds Banking Group",
    location: "Remote, UK",
    status: "applied" as const,
    appliedDate: "2026-05-20",
    followUpDate: "2026-05-27",
    notes: "Applied via CV-Library. Tailored CV to highlight Azure DevOps and banking experience.",
    matchScore: 88,
  },
  {
    id: "a3",
    jobTitle: "Azure Cloud Architect",
    company: "KPMG Digital",
    location: "London, UK",
    status: "applied" as const,
    appliedDate: "2026-05-18",
    followUpDate: "2026-05-25",
    notes: "Submitted via LinkedIn. Cover letter focused on enterprise architecture and client-facing experience.",
    matchScore: 87,
  },
  {
    id: "a4",
    jobTitle: "Cloud Platform Engineer",
    company: "Goldman Sachs",
    location: "London, UK",
    status: "offered" as const,
    appliedDate: "2026-05-01",
    followUpDate: null,
    notes: "Offer received: £118k + bonus. Reviewing package. Decision needed by 30th May.",
    matchScore: 85,
  },
  {
    id: "a5",
    jobTitle: "SRE Lead",
    company: "HSBC Technology",
    location: "Canary Wharf, UK",
    status: "rejected" as const,
    appliedDate: "2026-04-28",
    followUpDate: null,
    notes: "Rejected after first interview. Feedback: wanted more financial services domain experience.",
    matchScore: 71,
  },
  {
    id: "a6",
    jobTitle: "Platform Engineer — GCP",
    company: "Sky Technology",
    location: "Osterley, UK",
    status: "saved" as const,
    appliedDate: null,
    followUpDate: null,
    notes: "Interesting role but GCP focus — need to tailor CV. Apply before 1st June.",
    matchScore: 79,
  },
]

export const mockGeneratedDocuments = [
  {
    id: "d1",
    type: "tailored_cv",
    jobTitle: "Senior DevOps Engineer",
    company: "Barclays Technology",
    createdAt: "2026-05-14",
    atsScore: 94,
    fileName: "Hitendra_CV_Barclays_DevOps.docx",
  },
  {
    id: "d2",
    type: "cover_letter",
    jobTitle: "Senior DevOps Engineer",
    company: "Barclays Technology",
    createdAt: "2026-05-14",
    atsScore: null,
    fileName: "Hitendra_CoverLetter_Barclays.docx",
  },
  {
    id: "d3",
    type: "tailored_cv",
    jobTitle: "Azure Cloud Architect",
    company: "KPMG Digital",
    createdAt: "2026-05-17",
    atsScore: 91,
    fileName: "Hitendra_CV_KPMG_Azure.docx",
  },
]

export const mockSuggestedActions = [
  {
    id: "sa1",
    icon: "FileText",
    title: "Tailor CV for Senior DevOps Engineer role",
    subtitle: "Barclays Technology · Match score: 92%",
    priority: "high",
    href: "/cv-agent",
  },
  {
    id: "sa2",
    icon: "MessageSquare",
    title: "Prepare for Azure Platform Engineer interview",
    subtitle: "Scheduled 28 May · 3 days away",
    priority: "high",
    href: "/interview-prep",
  },
  {
    id: "sa3",
    icon: "Bell",
    title: "Follow up with recruiter — Cloud Consultant role",
    subtitle: "Lloyds Banking Group · Applied 6 days ago",
    priority: "medium",
    href: "/applications",
  },
  {
    id: "sa4",
    icon: "Linkedin",
    title: "Improve LinkedIn About section",
    subtitle: "Add 3 missing keywords to boost recruiter visibility",
    priority: "low",
    href: "/profile",
  },
]

export const mockInterviewQuestions = [
  {
    id: "q1",
    question: "Walk me through how you would design a Kubernetes-based deployment pipeline for a microservices application in a regulated financial environment.",
    difficulty: "hard",
    category: "Technical",
    keywordsToUse: [],
    starFramework: {
      situation: "Describe a regulated environment you've worked in (e.g. banking, healthcare)",
      task: "The requirement to deploy microservices safely with full audit trails and rollback capability",
      action: "GitOps with ArgoCD, image signing with Cosign, admission controllers, namespace-level RBAC, and immutable audit logs shipped to SIEM",
      result: "Zero production incidents from deployments, passed PCI DSS audit, 60% faster release cycles",
    },
  },
  {
    id: "q2",
    question: "How do you approach defining SLOs and SLIs for a high-traffic API service?",
    difficulty: "medium",
    category: "SRE",
    keywordsToUse: [],
    starFramework: {
      situation: "A payments API with 99.95% availability requirement and 200ms p99 latency target",
      task: "Define measurable SLOs that the team could act on and that aligned with user experience",
      action: "Worked with product and engineering to define availability, latency, and error rate SLIs. Set error budgets in Prometheus, built burn-rate alerts",
      result: "Team had clear signal on reliability debt, error budget consumed less than 20% quarterly",
    },
  },
  {
    id: "q3",
    question: "Describe your experience with infrastructure cost optimisation on cloud platforms.",
    difficulty: "medium",
    category: "Cloud",
    keywordsToUse: [],
    starFramework: {
      situation: "AWS bill growing 40% month-over-month with a startup scaling rapidly",
      task: "Reduce cloud spend without impacting performance or reliability",
      action: "Right-sized EC2 instances, adopted Spot for non-critical workloads, implemented S3 lifecycle policies, reserved capacity for baseline load, built cost dashboards per team",
      result: "Reduced monthly AWS spend by 34% while supporting 2× traffic growth",
    },
  },
  {
    id: "q4",
    question: "How have you handled a major production incident? Walk me through your incident response process.",
    difficulty: "hard",
    category: "SRE",
    keywordsToUse: [],
    starFramework: {
      situation: "A database failover caused 45 minutes of downtime for a B2C payments platform",
      task: "Restore service, communicate clearly, and prevent recurrence",
      action: "Declared SEV1, assembled on-call team, performed structured diagnosis with runbooks, restored from replica. Post-incident review identified missing heartbeat check and manual failover gap",
      result: "Full RCA published within 24 hours, automated failover implemented, zero repeat incidents in 18 months",
    },
  },
  {
    id: "q5",
    question: "What is your approach to mentoring junior engineers and building DevOps culture in an organisation?",
    difficulty: "easy",
    category: "Leadership",
    keywordsToUse: [],
    starFramework: {
      situation: "A team of 3 junior engineers with limited cloud experience joining a mature DevOps organisation",
      task: "Upskill the team and embed DevOps practices without slowing delivery",
      action: "Structured pair programming sessions, created internal runbooks, ran weekly 'cloud hours', gave junior engineers ownership of low-risk infrastructure changes with review",
      result: "All three engineers passed AWS Associate certifications within 6 months. Team velocity increased as senior engineers were freed from toil",
    },
  },
]
